stages:
  split_data:
    cmd: python src/data/split_data.py
    deps:
    - data/raw_data/raw.csv
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalization_data:
    cmd: python src/data/normalization_data.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch_best_parameters:
    cmd: python src/models/gridsearch_best_parameters.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    outs:
    - models/best_params.pkl
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    outs:
    - models/random_forest_model.pkl
